name: PR Review (MCP)
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, ready_for_review]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    if: ${{ github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - name: MCP ReviewKit
        uses: PRHatte/mcp-reviewkit@v1
        with:
          config: .github/pr-reviewer.yml
          fail-on: error
          enable-llm: ${{ secrets.OPENAI_API_KEY && 'true' || 'false' }}
          mcp-github-url: ${{ secrets.MCP_GITHUB_URL }}
          mcp-confluence-url: ${{ secrets.MCP_CONFLUENCE_URL }}
          mcp-jira-url: ${{ secrets.MCP_JIRA_URL }}
        env:
          MCP_AUTH_TOKEN: ${{ secrets.MCP_AUTH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  commands:
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && (startsWith(github.event.comment.body, '/create-jira') || startsWith(github.event.comment.body, '/jira')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
      - name: MCP ReviewKit (commands)
        uses: PRHatte/mcp-reviewkit@v1
        with:
          config: .github/pr-reviewer.yml
          fail-on: none
          mcp-github-url: ${{ secrets.MCP_GITHUB_URL }}
          mcp-jira-url: ${{ secrets.MCP_JIRA_URL }}
        env:
          MCP_AUTH_TOKEN: ${{ secrets.MCP_AUTH_TOKEN }}
